os: windows
language: cpp
branches:
  only:
  - master
env:
- _INPEEM_GIT_DIR=C:\\Users\\travis\\build\\INPE-EM\\inpeem _INPEEM_TERRAME_DIR="$(pwd)/solution/3rdparty/terrame"
install:
- choco install nsis -y
before_script:
- mkdir solution
- cd solution
- mkdir tests
- mkdir 3rdparty
- cd 3rdparty
- curl -L -s -O https://github.com/TerraME/terrame/releases/download/2.0.1/terrame-2.0.1-win64.zip
- 7z x terrame-2.0.1-win64.zip
- mv terrame-2.0.1-win64 terrame
- cd ..
- cp ../build/scripts/win/inpeem-conf.bat .
script:
- cmd //C inpeem-conf.bat
- export PATH_BACKUP=$PATH
- export TME_PATH="$(pwd)/install/terrame/bin"
- export PATH=$TME_PATH:$PATH
- cd tests
- cmd //C terrame -version
- cmd //C terrame -package inpeem -test
- cd $TRAVIS_BUILD_DIR
- export PATH=$PATH_BACKUP
deploy:
  provider: releases
  api_key:
    secure: TZh7Mtr8teMkpATZsj2UauyDG5MZIr4d3jagifWyasMSc/A0yZEF0Zj4tv+n4Ece3lI3QZeQ3EjGn82ffNaEEHLuxwfyW60B/HZFe5ui8oRI3rGWSaEsLH7JhZSgXramY5k76cYuzRj4bn3INTG32cJXVC+gVX2pu1vOzZY4xRgg+Vr4B15wLW8T4aSLhp8EtkSO6QhF6i24WlCpYyK/SZIdg1Cb+ikE6/jPOFTYy+FnGvGrYJt3cvQyrnD1RziLm8CZPHYclV/vu2Y/Xwp0larpWZXhL3X7dkCS3d3q3hzutCpq/vSlNm+lwuesuJpadyUdrEth4YqYC2Z2ibRf1BWY7+H/HTRMkS2K8A9XD+QOV/97ErfuMTlW0fOsIqJ76ZNALYfufdOYxY9n97TzryrNzhnElj1tqKOos8TCoYeIgaWuMAzkxTkfhRcM6nZSaMSVLKT1SLeLREhelr3r2mF9hSuO9ZPQuc8g/5SQ0D8bvJWSYWth6UpyilulSbnBj98wVXqvFl8bcO2PQJMUwvMfmvuQlyfk4IBXh397B+KLujwCRHNjjm3EMdr7KSkuDPkHZ8m+f6v+lqxPnTpW+61Dz7qyhvnH0vsnCHu+ATjkdkpWgDMs4CjEOuJDI2fWD7NgAUpYdpPCs0MQc77D70i7RXV0WX6k8GplDo9grg8=
  file_glob: true
  file: solution/build/installer/*.exe
  on:
    repo: INPE-EM/inpeem
  skip_cleanup: 'true'
  draft: true
