os: windows
language: cpp
branches:
  only:
  - master
env:
- _INPEEM_GIT_DIR=C:\\Users\\travis\\build\\INPE-EM\\inpeem _INPEEM_TERRAME_DIR="$(pwd)/solution/3rdparty/terrame"
install:
- choco install nsis -y
before_script:
- mkdir solution
- cd solution
- mkdir tests
- mkdir 3rdparty
- cd 3rdparty
- curl -L -s -O https://github.com/TerraME/terrame/releases/download/2.0.1/terrame-2.0.1-win64.zip
- 7z x terrame-2.0.1-win64.zip
- mv terrame-2.0.1-win64 terrame
- cd ..
- cp ../build/scripts/win/inpeem-conf.bat .
script:
- cmd //C inpeem-conf.bat
- export PATH_BACKUP=$PATH
- export TME_PATH="$(pwd)/install/terrame/bin"
- export PATH=$TME_PATH:$PATH
- cd tests
- cmd //C terrame -version
- cmd //C terrame -package inpeem -test
- cd ..
- export PATH=$PATH_BACKUP
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  deployment_file: true
  verbose: true
  file: "$TRAVIS_BUILD_DIR/solution/build/installer/INPE-EM-4.1.exe"
  on:
    branch: master
