version: 1.0.{build}

image:
  - Visual Studio 2017

branches:
  only:
    - master
    - qt-gui

skip_tags: true

clone_folder: C:\projects\git\inpeem

install:
  - cd C:\projects
  - mkdir 3rdparty
  - cd 3rdparty
  - curl -L -s -O https://github.com/TerraME/terrame/releases/download/2.0.1/terrame-2.0.1-win64.zip
  - 7z x terrame-2.0.1-win64.zip
  - mv terrame-2.0.1-win64 terrame
  - set _INPEEM_TERRAME_DIR=%CD%\terrame
  - cd ..
  - mkdir solution
  - cd solution
  - xcopy /Y ..\git\inpeem\build\scripts\win\inpeem_conf.bat %CD%
  - inpeem_conf.bat
