version: 1.0.{build}

branches:
  only:
    - master
    - qt-gui

skip_tags: true

clone_folder: git\inpeem

install:
  - mkdir solution
  - mkdir 3rdparty
  - cd solution
  - xcopy /Y ..\git\inpeem\build\scripts\win\inpeem_conf.bat %CD%
  - inpeem_conf.bat
