data{
	file = "amzCs5km_epsg29101.shp",
	summary = "",
	source = "",
	reference = "",
	attributes = {
		b3_agb = "",
		b3_perc1 = "",
		b3_perc2 = "",
		b3_perc3 = "",
		col = "",
		d_area06 = "",
		d_area07 = "",
		d_area08 = "",
		d_area09 = "",
		d_area10 = "",
		d_area11 = "",
		d_area12 = "",
		d_area13 = "",
		d_area14 = "",
		d_area15 = "",
		d_area16 = "",
		d_forest = "",
		d_inita = "",
		dg_darea06 = "",
		dg_darea07 = "",
		dg_darea08 = "",
		dg_darea09 = "",
		dg_darea10 = "",
		dg_darea11 = "",
		dg_darea12 = "",
		dg_darea13 = "",
		dg_darea14 = "",
		id = "",
		row = "",
	}
}

data{
	file = "amzCs5km_netemissions_epsg5880.shp",
	summary = "",
	source = "",
	reference = "",
	attributes = {
		O = "",
		b3_agb = "",
		b3_perc1 = "",
		b3_perc2 = "",
		b3_perc3 = "",
		col = "",
		d_area02 = "",
		d_area03 = "",
		d_area04 = "",
		d_area05 = "",
		d_area06 = "",
		d_area07 = "",
		d_area08 = "",
		d_area09 = "",
		d_area10 = "",
		d_area11 = "",
		d_area12 = "",
		d_area13 = "",
		d_area14 = "",
		d_area15 = "",
		d_area16 = "",
		d_forest = "",
		d_inita = "",
		d06 = "",
		dg_darea07 = "",
		dg_darea08 = "",
		dg_darea09 = "",
		dg_darea10 = "",
		dg_darea11 = "",
		dg_darea12 = "",
		dg_darea13 = "",
		dg_darea14 = "",
		dg_darea15 = "",
		dg_darea16 = "",
		for07 = "",
		id = "",
		outro = "",
		pTrjCrRaso = "",
		pTrjDegrad = "",
		pTrjRegen = "",
		row = "",
	}
}

